name: blueprint
region: nyc
services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /api/health
    envs:
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    github:
      branch: main
      deploy_on_push: true
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}
